function __define_tput_colors_additional_256terms() {



 #-------------------------------
 #
 # HANDY COLOR VARS
 #
 # SAFE to use in the oldests of
 # TERMS
 #
 #-------------------------------




  #FOREGROUND COLORS
  __0_=$(   tput setf 0   || tput setaf 0   || : 2>/dev/null  );
  export __1_=$(   tput setf 1   || tput setaf 1   || : 2>/dev/null  );
  export __2_=$(   tput setf 2   || tput setaf 2   || : 2>/dev/null  );
  export __3_=$(   tput setf 3   || tput setaf 3   || : 2>/dev/null  );
  export __4_=$(   tput setf 4   || tput setaf 4   || : 2>/dev/null  );
  export __5_=$(   tput setf 5   || tput setaf 5   || : 2>/dev/null  );
  export __6_=$(   tput setf 6   || tput setaf 6   || : 2>/dev/null  );
  export __7_=$(   tput setf 7   || tput setaf 7   || : 2>/dev/null  );
  export __8_=$(   tput setf 8   || tput setaf 8   || : 2>/dev/null  );
  export __9_=$(   tput setf 9   || tput setaf 9   || : 2>/dev/null  );
  export __10_=$(  tput setf 10  || tput setaf 10  || : 2>/dev/null  );
  export __11_=$(  tput setf 11  || tput setaf 11  || : 2>/dev/null  );
  export __12_=$(  tput setf 12  || tput setaf 12  || : 2>/dev/null  );
  export __13_=$(  tput setf 13  || tput setaf 13  || : 2>/dev/null  );
  export __14_=$(  tput setf 14  || tput setaf 14  || : 2>/dev/null  );
  export __15_=$(  tput setf 15  || tput setaf 15  || : 2>/dev/null  );
  export __16_=$(  tput setf 16  || tput setaf 16  || : 2>/dev/null  );
  export __17_=$(  tput setf 17  || tput setaf 17  || : 2>/dev/null  ); # SET FG color to NavyBlue
  export __18_=$(  tput setf 18  || tput setaf 18  || : 2>/dev/null  ); # SET FG color to DarkBlue
  export __19_=$(  tput setf 19  || tput setaf 19  || : 2>/dev/null  ); # SET FG color to Blue3
  export __20_=$(  tput setf 20  || tput setaf 20  || : 2>/dev/null  ); # SET FG color to Blue3
  export __21_=$(  tput setf 21  || tput setaf 21  || : 2>/dev/null  ); # SET FG color to Blue1
  export __22_=$(  tput setf 22  || tput setaf 22  || : 2>/dev/null  ); # SET FG color to DarkGreen
  export __23_=$(  tput setf 23  || tput setaf 23  || : 2>/dev/null  ); # SET FG color to DeepSkyBlue4
  export __24_=$(  tput setf 24  || tput setaf 24  || : 2>/dev/null  ); # SET FG color to DeepSkyBlue4
  export __25_=$(  tput setf 25  || tput setaf 25  || : 2>/dev/null  ); # SET FG color to DeepSkyBlue4
  export __26_=$(  tput setf 26  || tput setaf 26  || : 2>/dev/null  ); # SET FG color to DodgerBlue3
  export __27_=$(  tput setf 27  || tput setaf 27  || : 2>/dev/null  ); # SET FG color to DodgerBlue2
  export __28_=$(  tput setf 28  || tput setaf 28  || : 2>/dev/null  ); # SET FG color to Green4
  export __29_=$(  tput setf 29  || tput setaf 29  || : 2>/dev/null  ); # SET FG color to SpringGreen4
  export __30_=$(  tput setf 30  || tput setaf 30  || : 2>/dev/null  ); # SET FG color to Turquoise4
  export __31_=$(  tput setf 31  || tput setaf 31  || : 2>/dev/null  ); # SET FG color to DeepSkyBlue3
  export __32_=$(  tput setf 32  || tput setaf 32  || : 2>/dev/null  ); # SET FG color to DeepSkyBlue3
  export __33_=$(  tput setf 33  || tput setaf 33  || : 2>/dev/null  ); # SET FG color to DodgerBlue1
  export __34_=$(  tput setf 34  || tput setaf 34  || : 2>/dev/null  ); # SET FG color to Green3
  export __35_=$(  tput setf 35  || tput setaf 35  || : 2>/dev/null  ); # SET FG color to SpringGreen3
  export __36_=$(  tput setf 36  || tput setaf 36  || : 2>/dev/null  ); # SET FG color to DarkCyan
  export __37_=$(  tput setf 37  || tput setaf 37  || : 2>/dev/null  ); # SET FG color to LightSeaGreen
  export __38_=$(  tput setf 38  || tput setaf 38  || : 2>/dev/null  ); # SET FG color to DeepSkyBlue2
  export __39_=$(  tput setf 39  || tput setaf 39  || : 2>/dev/null  ); # SET FG color to DeepSkyBlue1
  export __40_=$(  tput setf 40  || tput setaf 40  || : 2>/dev/null  ); # SET FG color to Green3
  export __41_=$(  tput setf 41  || tput setaf 41  || : 2>/dev/null  ); # SET FG color to SpringGreen3
  export __42_=$(  tput setf 42  || tput setaf 42  || : 2>/dev/null  ); # SET FG color to SpringGreen2
  export __43_=$(  tput setf 43  || tput setaf 43  || : 2>/dev/null  ); # SET FG color to Cyan3
  export __44_=$(  tput setf 44  || tput setaf 44  || : 2>/dev/null  ); # SET FG color to DarkTurquoise
  export __45_=$(  tput setf 45  || tput setaf 45  || : 2>/dev/null  ); # SET FG color to Turquoise2
  export __46_=$(  tput setf 46  || tput setaf 46  || : 2>/dev/null  ); # SET FG color to Green1
  export __47_=$(  tput setf 47  || tput setaf 47  || : 2>/dev/null  ); # SET FG color to SpringGreen2
  export __48_=$(  tput setf 48  || tput setaf 48  || : 2>/dev/null  ); # SET FG color to SpringGreen1
  export __49_=$(  tput setf 49  || tput setaf 49  || : 2>/dev/null  ); # SET FG color to MediumSpringGreen
  export __50_=$(  tput setf 50  || tput setaf 50  || : 2>/dev/null  ); # SET FG color to Cyan2
  export __51_=$(  tput setf 51  || tput setaf 51  || : 2>/dev/null  ); # SET FG color to Cyan1
  export __52_=$(  tput setf 52  || tput setaf 52  || : 2>/dev/null  ); # SET FG color to DarkRed
  export __53_=$(  tput setf 53  || tput setaf 53  || : 2>/dev/null  ); # SET FG color to DeepPink4
  export __54_=$(  tput setf 54  || tput setaf 54  || : 2>/dev/null  ); # SET FG color to Purple4
  export __55_=$(  tput setf 55  || tput setaf 55  || : 2>/dev/null  ); # SET FG color to Purple4
  export __56_=$(  tput setf 56  || tput setaf 56  || : 2>/dev/null  ); # SET FG color to Purple3
  export __57_=$(  tput setf 57  || tput setaf 57  || : 2>/dev/null  ); # SET FG color to BlueViolet
  export __58_=$(  tput setf 58  || tput setaf 58  || : 2>/dev/null  ); # SET FG color to Orange4
  export __59_=$(  tput setf 59  || tput setaf 59  || : 2>/dev/null  ); # SET FG color to Grey37
  export __60_=$(  tput setf 60  || tput setaf 60  || : 2>/dev/null  ); # SET FG color to MediumPurple4
  export __61_=$(  tput setf 61  || tput setaf 61  || : 2>/dev/null  ); # SET FG color to SlateBlue3
  export __62_=$(  tput setf 62  || tput setaf 62  || : 2>/dev/null  ); # SET FG color to SlateBlue3
  export __63_=$(  tput setf 63  || tput setaf 63  || : 2>/dev/null  ); # SET FG color to RoyalBlue1
  export __64_=$(  tput setf 64  || tput setaf 64  || : 2>/dev/null  ); # SET FG color to Chartreuse4
  export __65_=$(  tput setf 65  || tput setaf 65  || : 2>/dev/null  ); # SET FG color to DarkSeaGreen4
  export __66_=$(  tput setf 66  || tput setaf 66  || : 2>/dev/null  ); # SET FG color to PaleTurquoise4
  export __67_=$(  tput setf 67  || tput setaf 67  || : 2>/dev/null  ); # SET FG color to SteelBlue
  export __68_=$(  tput setf 68  || tput setaf 68  || : 2>/dev/null  ); # SET FG color to SteelBlue3
  export __69_=$(  tput setf 69  || tput setaf 69  || : 2>/dev/null  ); # SET FG color to CornflowerBlue
  export __70_=$(  tput setf 70  || tput setaf 70  || : 2>/dev/null  ); # SET FG color to Chartreuse3
  export __71_=$(  tput setf 71  || tput setaf 71  || : 2>/dev/null  ); # SET FG color to DarkSeaGreen4
  export __72_=$(  tput setf 72  || tput setaf 72  || : 2>/dev/null  ); # SET FG color to CadetBlue
  export __73_=$(  tput setf 73  || tput setaf 73  || : 2>/dev/null  ); # SET FG color to CadetBlue
  export __74_=$(  tput setf 74  || tput setaf 74  || : 2>/dev/null  ); # SET FG color to SkyBlue3
  export __75_=$(  tput setf 75  || tput setaf 75  || : 2>/dev/null  ); # SET FG color to SteelBlue1
  export __76_=$(  tput setf 76  || tput setaf 76  || : 2>/dev/null  ); # SET FG color to Chartreuse3
  export __77_=$(  tput setf 77  || tput setaf 77  || : 2>/dev/null  ); # SET FG color to PaleGreen3
  export __78_=$(  tput setf 78  || tput setaf 78  || : 2>/dev/null  ); # SET FG color to SeaGreen3
  export __79_=$(  tput setf 79  || tput setaf 79  || : 2>/dev/null  ); # SET FG color to Aquamarine3
  export __80_=$(  tput setf 80  || tput setaf 80  || : 2>/dev/null  ); # SET FG color to MediumTurquoise
  export __81_=$(  tput setf 81  || tput setaf 81  || : 2>/dev/null  ); # SET FG color to SteelBlue1
  export __82_=$(  tput setf 82  || tput setaf 82  || : 2>/dev/null  ); # SET FG color to Chartreuse2
  export __83_=$(  tput setf 83  || tput setaf 83  || : 2>/dev/null  ); # SET FG color to SeaGreen2
  export __84_=$(  tput setf 84  || tput setaf 84  || : 2>/dev/null  ); # SET FG color to SeaGreen1
  export __85_=$(  tput setf 85  || tput setaf 85  || : 2>/dev/null  ); # SET FG color to SeaGreen1
  export __86_=$(  tput setf 86  || tput setaf 86  || : 2>/dev/null  ); # SET FG color to Aquamarine1
  export __87_=$(  tput setf 87  || tput setaf 87  || : 2>/dev/null  ); # SET FG color to DarkSlateGray2
  export __88_=$(  tput setf 88  || tput setaf 88  || : 2>/dev/null  ); # SET FG color to DarkRed
  export __89_=$(  tput setf 89  || tput setaf 89  || : 2>/dev/null  ); # SET FG color to DeepPink4
  export __90_=$(  tput setf 90  || tput setaf 90  || : 2>/dev/null  ); # SET FG color to DarkMagenta
  export __91_=$(  tput setf 91  || tput setaf 91  || : 2>/dev/null  ); # SET FG color to DarkMagenta
  export __92_=$(  tput setf 92  || tput setaf 92  || : 2>/dev/null  ); # SET FG color to DarkViolet
  export __93_=$(  tput setf 93  || tput setaf 93  || : 2>/dev/null  ); # SET FG color to Purple
  export __94_=$(  tput setf 94  || tput setaf 94  || : 2>/dev/null  ); # SET FG color to Orange4
  export __95_=$(  tput setf 95  || tput setaf 95  || : 2>/dev/null  ); # SET FG color to LightPink4
  export __96_=$(  tput setf 96  || tput setaf 96  || : 2>/dev/null  ); # SET FG color to Plum4
  export __97_=$(  tput setf 97  || tput setaf 97  || : 2>/dev/null  ); # SET FG color to MediumPurple3
  export __98_=$(  tput setf 98  || tput setaf 98  || : 2>/dev/null  ); # SET FG color to MediumPurple3
  export __99_=$(  tput setf 99  || tput setaf 99  || : 2>/dev/null  ); # SET FG color to SlateBlue1
  export __100_=$( tput setf 100 || tput setaf 100 || : 2>/dev/null ); # SET FG color to Yellow4
  export __101_=$( tput setf 101 || tput setaf 101 || : 2>/dev/null ); # SET FG color to Wheat4
  export __102_=$( tput setf 102 || tput setaf 102 || : 2>/dev/null ); # SET FG color to Grey53
  export __103_=$( tput setf 103 || tput setaf 103 || : 2>/dev/null ); # SET FG color to LightSlateGrey
  export __104_=$( tput setf 104 || tput setaf 104 || : 2>/dev/null ); # SET FG color to MediumPurple
  export __105_=$( tput setf 105 || tput setaf 105 || : 2>/dev/null ); # SET FG color to LightSlateBlue
  export __106_=$( tput setf 106 || tput setaf 106 || : 2>/dev/null ); # SET FG color to Yellow4
  export __107_=$( tput setf 107 || tput setaf 107 || : 2>/dev/null ); # SET FG color to DarkOliveGreen3
  export __108_=$( tput setf 108 || tput setaf 108 || : 2>/dev/null ); # SET FG color to DarkSeaGreen
  export __109_=$( tput setf 109 || tput setaf 109 || : 2>/dev/null ); # SET FG color to LightSkyBlue3
  export __110_=$( tput setf 110 || tput setaf 110 || : 2>/dev/null ); # SET FG color to LightSkyBlue3
  export __111_=$( tput setf 111 || tput setaf 111 || : 2>/dev/null ); # SET FG color to SkyBlue2
  export __112_=$( tput setf 112 || tput setaf 112 || : 2>/dev/null ); # SET FG color to Chartreuse2
  export __113_=$( tput setf 113 || tput setaf 113 || : 2>/dev/null ); # SET FG color to DarkOliveGreen3
  export __114_=$( tput setf 114 || tput setaf 114 || : 2>/dev/null ); # SET FG color to PaleGreen3
  export __115_=$( tput setf 115 || tput setaf 115 || : 2>/dev/null ); # SET FG color to DarkSeaGreen3
  export __116_=$( tput setf 116 || tput setaf 116 || : 2>/dev/null ); # SET FG color to DarkSlateGray3
  export __117_=$( tput setf 117 || tput setaf 117 || : 2>/dev/null ); # SET FG color to SkyBlue1
  export __118_=$( tput setf 118 || tput setaf 118 || : 2>/dev/null ); # SET FG color to Chartreuse1
  export __119_=$( tput setf 119 || tput setaf 119 || : 2>/dev/null ); # SET FG color to LightGreen
  export __120_=$( tput setf 120 || tput setaf 120 || : 2>/dev/null ); # SET FG color to LightGreen
  export __121_=$( tput setf 121 || tput setaf 121 || : 2>/dev/null ); # SET FG color to PaleGreen1
  export __122_=$( tput setf 122 || tput setaf 122 || : 2>/dev/null ); # SET FG color to Aquamarine1
  export __123_=$( tput setf 123 || tput setaf 123 || : 2>/dev/null ); # SET FG color to DarkSlateGray1
  export __124_=$( tput setf 124 || tput setaf 124 || : 2>/dev/null ); # SET FG color to Red3
  export __125_=$( tput setf 125 || tput setaf 125 || : 2>/dev/null ); # SET FG color to DeepPink4
  export __126_=$( tput setf 126 || tput setaf 126 || : 2>/dev/null ); # SET FG color to MediumVioletRed
  export __127_=$( tput setf 127 || tput setaf 127 || : 2>/dev/null ); # SET FG color to Magenta3
  export __128_=$( tput setf 128 || tput setaf 128 || : 2>/dev/null ); # SET FG color to DarkViolet
  export __129_=$( tput setf 129 || tput setaf 129 || : 2>/dev/null ); # SET FG color to Purple
  export __130_=$( tput setf 130 || tput setaf 130 || : 2>/dev/null ); # SET FG color to DarkOrange3
  export __131_=$( tput setf 131 || tput setaf 131 || : 2>/dev/null ); # SET FG color to IndianRed
  export __132_=$( tput setf 132 || tput setaf 132 || : 2>/dev/null ); # SET FG color to HotPink3
  export __133_=$( tput setf 133 || tput setaf 133 || : 2>/dev/null ); # SET FG color to MediumOrchid3
  export __134_=$( tput setf 134 || tput setaf 134 || : 2>/dev/null ); # SET FG color to MediumOrchid
  export __135_=$( tput setf 135 || tput setaf 135 || : 2>/dev/null ); # SET FG color to MediumPurple2
  export __136_=$( tput setf 136 || tput setaf 136 || : 2>/dev/null ); # SET FG color to DarkGoldenrod
  export __137_=$( tput setf 137 || tput setaf 137 || : 2>/dev/null ); # SET FG color to LightSalmon3
  export __138_=$( tput setf 138 || tput setaf 138 || : 2>/dev/null ); # SET FG color to RosyBrown
  export __139_=$( tput setf 139 || tput setaf 139 || : 2>/dev/null ); # SET FG color to Grey63
  export __140_=$( tput setf 140 || tput setaf 140 || : 2>/dev/null ); # SET FG color to MediumPurple2
  export __141_=$( tput setf 141 || tput setaf 141 || : 2>/dev/null ); # SET FG color to MediumPurple1
  export __142_=$( tput setf 142 || tput setaf 142 || : 2>/dev/null ); # SET FG color to Gold3
  export __143_=$( tput setf 143 || tput setaf 143 || : 2>/dev/null ); # SET FG color to DarkKhaki
  export __144_=$( tput setf 144 || tput setaf 144 || : 2>/dev/null ); # SET FG color to NavajoWhite3
  export __145_=$( tput setf 145 || tput setaf 145 || : 2>/dev/null ); # SET FG color to Grey69
  export __146_=$( tput setf 146 || tput setaf 146 || : 2>/dev/null ); # SET FG color to LightSteelBlue3
  export __147_=$( tput setf 147 || tput setaf 147 || : 2>/dev/null ); # SET FG color to LightSteelBlue
  export __148_=$( tput setf 148 || tput setaf 148 || : 2>/dev/null ); # SET FG color to Yellow3
  export __149_=$( tput setf 149 || tput setaf 149 || : 2>/dev/null ); # SET FG color to DarkOliveGreen3
  export __150_=$( tput setf 150 || tput setaf 150 || : 2>/dev/null ); # SET FG color to DarkSeaGreen3
  export __151_=$( tput setf 151 || tput setaf 151 || : 2>/dev/null ); # SET FG color to DarkSeaGreen2
  export __152_=$( tput setf 152 || tput setaf 152 || : 2>/dev/null ); # SET FG color to LightCyan3
  export __153_=$( tput setf 153 || tput setaf 153 || : 2>/dev/null ); # SET FG color to LightSkyBlue1
  export __154_=$( tput setf 154 || tput setaf 154 || : 2>/dev/null ); # SET FG color to GreenYellow
  export __155_=$( tput setf 155 || tput setaf 155 || : 2>/dev/null ); # SET FG color to DarkOliveGreen2
  export __156_=$( tput setf 156 || tput setaf 156 || : 2>/dev/null ); # SET FG color to PaleGreen1
  export __157_=$( tput setf 157 || tput setaf 157 || : 2>/dev/null ); # SET FG color to DarkSeaGreen2
  export __158_=$( tput setf 158 || tput setaf 158 || : 2>/dev/null ); # SET FG color to DarkSeaGreen1
  export __159_=$( tput setf 159 || tput setaf 159 || : 2>/dev/null ); # SET FG color to PaleTurquoise1
  export __160_=$( tput setf 160 || tput setaf 160 || : 2>/dev/null ); # SET FG color to Red3
  export __161_=$( tput setf 161 || tput setaf 161 || : 2>/dev/null ); # SET FG color to DeepPink3
  export __162_=$( tput setf 162 || tput setaf 162 || : 2>/dev/null ); # SET FG color to DeepPink3
  export __163_=$( tput setf 163 || tput setaf 163 || : 2>/dev/null ); # SET FG color to Magenta3
  export __164_=$( tput setf 164 || tput setaf 164 || : 2>/dev/null ); # SET FG color to Magenta3
  export __165_=$( tput setf 165 || tput setaf 165 || : 2>/dev/null ); # SET FG color to Magenta2
  export __166_=$( tput setf 166 || tput setaf 166 || : 2>/dev/null ); # SET FG color to DarkOrange3
  export __167_=$( tput setf 167 || tput setaf 167 || : 2>/dev/null ); # SET FG color to IndianRed
  export __168_=$( tput setf 168 || tput setaf 168 || : 2>/dev/null ); # SET FG color to HotPink3
  export __169_=$( tput setf 169 || tput setaf 169 || : 2>/dev/null ); # SET FG color to HotPink2
  export __170_=$( tput setf 170 || tput setaf 170 || : 2>/dev/null ); # SET FG color to Orchid
  export __171_=$( tput setf 171 || tput setaf 171 || : 2>/dev/null ); # SET FG color to MediumOrchid1
  export __172_=$( tput setf 172 || tput setaf 172 || : 2>/dev/null ); # SET FG color to Orange3
  export __173_=$( tput setf 173 || tput setaf 173 || : 2>/dev/null ); # SET FG color to LightSalmon3
  export __174_=$( tput setf 174 || tput setaf 174 || : 2>/dev/null ); # SET FG color to LightPink3
  export __175_=$( tput setf 175 || tput setaf 175 || : 2>/dev/null ); # SET FG color to Pink3
  export __176_=$( tput setf 176 || tput setaf 176 || : 2>/dev/null ); # SET FG color to Plum3
  export __177_=$( tput setf 177 || tput setaf 177 || : 2>/dev/null ); # SET FG color to Violet
  export __178_=$( tput setf 178 || tput setaf 178 || : 2>/dev/null ); # SET FG color to Gold3
  export __179_=$( tput setf 179 || tput setaf 179 || : 2>/dev/null ); # SET FG color to LightGoldenrod3
  export __180_=$( tput setf 180 || tput setaf 180 || : 2>/dev/null ); # SET FG color to Tan
  export __181_=$( tput setf 181 || tput setaf 181 || : 2>/dev/null ); # SET FG color to MistyRose3
  export __182_=$( tput setf 182 || tput setaf 182 || : 2>/dev/null ); # SET FG color to Thistle3
  export __183_=$( tput setf 183 || tput setaf 183 || : 2>/dev/null ); # SET FG color to Plum2
  export __184_=$( tput setf 184 || tput setaf 184 || : 2>/dev/null ); # SET FG color to Yellow3
  export __185_=$( tput setf 185 || tput setaf 185 || : 2>/dev/null ); # SET FG color to Khaki3
  export __186_=$( tput setf 186 || tput setaf 186 || : 2>/dev/null ); # SET FG color to LightGoldenrod2
  export __187_=$( tput setf 187 || tput setaf 187 || : 2>/dev/null ); # SET FG color to LightYellow3
  export __188_=$( tput setf 188 || tput setaf 188 || : 2>/dev/null ); # SET FG color to Grey84
  export __189_=$( tput setf 189 || tput setaf 189 || : 2>/dev/null ); # SET FG color to LightSteelBlue1
  export __190_=$( tput setf 190 || tput setaf 190 || : 2>/dev/null ); # SET FG color to Yellow2
  export __191_=$( tput setf 191 || tput setaf 191 || : 2>/dev/null ); # SET FG color to DarkOliveGreen1
  export __192_=$( tput setf 192 || tput setaf 192 || : 2>/dev/null ); # SET FG color to DarkOliveGreen1
  export __193_=$( tput setf 193 || tput setaf 193 || : 2>/dev/null ); # SET FG color to DarkSeaGreen1
  export __194_=$( tput setf 194 || tput setaf 194 || : 2>/dev/null ); # SET FG color to Honeydew2
  export __195_=$( tput setf 195 || tput setaf 195 || : 2>/dev/null ); # SET FG color to LightCyan1
  export __196_=$( tput setf 196 || tput setaf 196 || : 2>/dev/null ); # SET FG color to Red1
  export __197_=$( tput setf 197 || tput setaf 197 || : 2>/dev/null ); # SET FG color to DeepPink2
  export __198_=$( tput setf 198 || tput setaf 198 || : 2>/dev/null ); # SET FG color to DeepPink1
  export __199_=$( tput setf 199 || tput setaf 199 || : 2>/dev/null ); # SET FG color to DeepPink1
  export __200_=$( tput setf 200 || tput setaf 200 || : 2>/dev/null ); # SET FG color to Magenta2
  export __201_=$( tput setf 201 || tput setaf 201 || : 2>/dev/null ); # SET FG color to Magenta1
  export __202_=$( tput setf 202 || tput setaf 202 || : 2>/dev/null ); # SET FG color to OrangeRed1
  export __203_=$( tput setf 203 || tput setaf 203 || : 2>/dev/null ); # SET FG color to IndianRed1
  export __204_=$( tput setf 204 || tput setaf 204 || : 2>/dev/null ); # SET FG color to IndianRed1
  export __205_=$( tput setf 205 || tput setaf 205 || : 2>/dev/null ); # SET FG color to HotPink
  export __206_=$( tput setf 206 || tput setaf 206 || : 2>/dev/null ); # SET FG color to HotPink
  export __207_=$( tput setf 207 || tput setaf 207 || : 2>/dev/null ); # SET FG color to MediumOrchid1
  export __208_=$( tput setf 208 || tput setaf 208 || : 2>/dev/null ); # SET FG color to DarkOrange
  export __209_=$( tput setf 209 || tput setaf 209 || : 2>/dev/null ); # SET FG color to Salmon1
  export __210_=$( tput setf 210 || tput setaf 210 || : 2>/dev/null ); # SET FG color to LightCoral
  export __211_=$( tput setf 211 || tput setaf 211 || : 2>/dev/null ); # SET FG color to PaleVioletRed1
  export __212_=$( tput setf 212 || tput setaf 212 || : 2>/dev/null ); # SET FG color to Orchid2
  export __213_=$( tput setf 213 || tput setaf 213 || : 2>/dev/null ); # SET FG color to Orchid1
  export __214_=$( tput setf 214 || tput setaf 214 || : 2>/dev/null ); # SET FG color to Orange1
  export __215_=$( tput setf 215 || tput setaf 215 || : 2>/dev/null ); # SET FG color to SandyBrown
  export __216_=$( tput setf 216 || tput setaf 216 || : 2>/dev/null ); # SET FG color to LightSalmon1
  export __217_=$( tput setf 217 || tput setaf 217 || : 2>/dev/null ); # SET FG color to LightPink1
  export __218_=$( tput setf 218 || tput setaf 218 || : 2>/dev/null ); # SET FG color to Pink1
  export __219_=$( tput setf 219 || tput setaf 219 || : 2>/dev/null ); # SET FG color to Plum1
  export __220_=$( tput setf 220 || tput setaf 220 || : 2>/dev/null ); # SET FG color to Gold1
  export __221_=$( tput setf 221 || tput setaf 221 || : 2>/dev/null ); # SET FG color to LightGoldenrod2
  export __222_=$( tput setf 222 || tput setaf 222 || : 2>/dev/null ); # SET FG color to LightGoldenrod2
  export __223_=$( tput setf 223 || tput setaf 223 || : 2>/dev/null ); # SET FG color to NavajoWhite1
  export __224_=$( tput setf 224 || tput setaf 224 || : 2>/dev/null ); # SET FG color to MistyRose1
  export __225_=$( tput setf 225 || tput setaf 225 || : 2>/dev/null ); # SET FG color to Thistle1
  export __226_=$( tput setf 226 || tput setaf 226 || : 2>/dev/null ); # SET FG color to Yellow1
  export __227_=$( tput setf 227 || tput setaf 227 || : 2>/dev/null ); # SET FG color to LightGoldenrod1
  export __228_=$( tput setf 228 || tput setaf 228 || : 2>/dev/null ); # SET FG color to Khaki1
  export __229_=$( tput setf 229 || tput setaf 229 || : 2>/dev/null ); # SET FG color to Wheat1
  export __230_=$( tput setf 230 || tput setaf 230 || : 2>/dev/null ); # SET FG color to Cornsilk1
  export __231_=$( tput setf 231 || tput setaf 231 || : 2>/dev/null ); # SET FG color to Grey100
  export __232_=$( tput setf 232 || tput setaf 232 || : 2>/dev/null ); # SET FG color to Grey3
  export __233_=$( tput setf 233 || tput setaf 233 || : 2>/dev/null ); # SET FG color to Grey7
  export __234_=$( tput setf 234 || tput setaf 234 || : 2>/dev/null ); # SET FG color to Grey11
  export __235_=$( tput setf 235 || tput setaf 235 || : 2>/dev/null ); # SET FG color to Grey15
  export __236_=$( tput setf 236 || tput setaf 236 || : 2>/dev/null ); # SET FG color to Grey19
  export __237_=$( tput setf 237 || tput setaf 237 || : 2>/dev/null ); # SET FG color to Grey23
  export __238_=$( tput setf 238 || tput setaf 238 || : 2>/dev/null ); # SET FG color to Grey27
  export __239_=$( tput setf 239 || tput setaf 239 || : 2>/dev/null ); # SET FG color to Grey30
  export __240_=$( tput setf 240 || tput setaf 240 || : 2>/dev/null ); # SET FG color to Grey35
  export __241_=$( tput setf 241 || tput setaf 241 || : 2>/dev/null ); # SET FG color to Grey39
  export __242_=$( tput setf 242 || tput setaf 242 || : 2>/dev/null ); # SET FG color to Grey42
  export __243_=$( tput setf 243 || tput setaf 243 || : 2>/dev/null ); # SET FG color to Grey46
  export __244_=$( tput setf 244 || tput setaf 244 || : 2>/dev/null ); # SET FG color to Grey50
  export __245_=$( tput setf 245 || tput setaf 245 || : 2>/dev/null ); # SET FG color to Grey54
  export __246_=$( tput setf 246 || tput setaf 246 || : 2>/dev/null ); # SET FG color to Grey58
  export __247_=$( tput setf 247 || tput setaf 247 || : 2>/dev/null ); # SET FG color to Grey62
  export __248_=$( tput setf 248 || tput setaf 248 || : 2>/dev/null ); # SET FG color to Grey66
  export __249_=$( tput setf 249 || tput setaf 249 || : 2>/dev/null ); # SET FG color to Grey70
  export __250_=$( tput setf 250 || tput setaf 250 || : 2>/dev/null ); # SET FG color to Grey74
  export __251_=$( tput setf 251 || tput setaf 251 || : 2>/dev/null ); # SET FG color to Grey78
  export __252_=$( tput setf 252 || tput setaf 252 || : 2>/dev/null ); # SET FG color to Grey82
  export __253_=$( tput setf 253 || tput setaf 253 || : 2>/dev/null ); # SET FG color to Grey85
  export __254_=$( tput setf 254 || tput setaf 254 || : 2>/dev/null ); # SET FG color to Grey89
  export __255_=$( tput setf 255 || tput setaf 255 || : 2>/dev/null ); # SET FG color to Grey93










  # BACKGROUND COLORS
  export __BG0_=$(   tput setb 0   || tput setab 0   || : 2>/dev/null  );
  export __BG1_=$(   tput setb 1   || tput setab 1   || : 2>/dev/null  );
  export __BG2_=$(   tput setb 2   || tput setab 2   || : 2>/dev/null  );
  export __BG3_=$(   tput setb 3   || tput setab 3   || : 2>/dev/null  );
  export __BG4_=$(   tput setb 4   || tput setab 4   || : 2>/dev/null  );
  export __BG5_=$(   tput setb 5   || tput setab 5   || : 2>/dev/null  );
  export __BG6_=$(   tput setb 6   || tput setab 6   || : 2>/dev/null  );
  export __BG7_=$(   tput setb 7   || tput setab 7   || : 2>/dev/null  );
  export __BG8_=$(   tput setb 8   || tput setab 8   || : 2>/dev/null  );
  export __BG9_=$(   tput setb 9   || tput setab 9   || : 2>/dev/null  );
  export __BG10_=$(  tput setb 10  || tput setab 10  || : 2>/dev/null  );
  export __BG11_=$(  tput setb 11  || tput setab 11  || : 2>/dev/null  );
  export __BG12_=$(  tput setb 12  || tput setab 12  || : 2>/dev/null  );
  export __BG13_=$(  tput setb 13  || tput setab 13  || : 2>/dev/null  );
  export __BG14_=$(  tput setb 14  || tput setab 14  || : 2>/dev/null  );
  export __BG15_=$(  tput setb 15  || tput setab 15  || : 2>/dev/null  );
  export __BG16_=$(  tput setb 16  || tput setab 16  || : 2>/dev/null  ); # SET BG color to Grey0
  export __BG17_=$(  tput setb 17  || tput setab 17  || : 2>/dev/null  ); # SET BG color to NavyBlue
  export __BG18_=$(  tput setb 18  || tput setab 18  || : 2>/dev/null  ); # SET BG color to DarkBlue
  export __BG19_=$(  tput setb 19  || tput setab 19  || : 2>/dev/null  ); # SET BG color to Blue3
  export __BG20_=$(  tput setb 20  || tput setab 20  || : 2>/dev/null  ); # SET BG color to Blue3
  export __BG21_=$(  tput setb 21  || tput setab 21  || : 2>/dev/null  ); # SET BG color to Blue1
  export __BG22_=$(  tput setb 22  || tput setab 22  || : 2>/dev/null  ); # SET BG color to DarkGreen
  export __BG23_=$(  tput setb 23  || tput setab 23  || : 2>/dev/null  ); # SET BG color to DeepSkyBlue4
  export __BG24_=$(  tput setb 24  || tput setab 24  || : 2>/dev/null  ); # SET BG color to DeepSkyBlue4
  export __BG25_=$(  tput setb 25  || tput setab 25  || : 2>/dev/null  ); # SET BG color to DeepSkyBlue4
  export __BG26_=$(  tput setb 26  || tput setab 26  || : 2>/dev/null  ); # SET BG color to DodgerBlue3
  export __BG27_=$(  tput setb 27  || tput setab 27  || : 2>/dev/null  ); # SET BG color to DodgerBlue2
  export __BG28_=$(  tput setb 28  || tput setab 28  || : 2>/dev/null  ); # SET BG color to Green4
  export __BG29_=$(  tput setb 29  || tput setab 29  || : 2>/dev/null  ); # SET BG color to SpringGreen4
  export __BG30_=$(  tput setb 30  || tput setab 30  || : 2>/dev/null  ); # SET BG color to Turquoise4
  export __BG31_=$(  tput setb 31  || tput setab 31  || : 2>/dev/null  ); # SET BG color to DeepSkyBlue3
  export __BG32_=$(  tput setb 32  || tput setab 32  || : 2>/dev/null  ); # SET BG color to DeepSkyBlue3
  export __BG33_=$(  tput setb 33  || tput setab 33  || : 2>/dev/null  ); # SET BG color to DodgerBlue1
  export __BG34_=$(  tput setb 34  || tput setab 34  || : 2>/dev/null  ); # SET BG color to Green3
  export __BG35_=$(  tput setb 35  || tput setab 35  || : 2>/dev/null  ); # SET BG color to SpringGreen3
  export __BG36_=$(  tput setb 36  || tput setab 36  || : 2>/dev/null  ); # SET BG color to DarkCyan
  export __BG37_=$(  tput setb 37  || tput setab 37  || : 2>/dev/null  ); # SET BG color to LightSeaGreen
  export __BG38_=$(  tput setb 38  || tput setab 38  || : 2>/dev/null  ); # SET BG color to DeepSkyBlue2
  export __BG39_=$(  tput setb 39  || tput setab 39  || : 2>/dev/null  ); # SET BG color to DeepSkyBlue1
  export __BG40_=$(  tput setb 40  || tput setab 40  || : 2>/dev/null  ); # SET BG color to Green3
  export __BG41_=$(  tput setb 41  || tput setab 41  || : 2>/dev/null  ); # SET BG color to SpringGreen3
  export __BG42_=$(  tput setb 42  || tput setab 42  || : 2>/dev/null  ); # SET BG color to SpringGreen2
  export __BG43_=$(  tput setb 43  || tput setab 43  || : 2>/dev/null  ); # SET BG color to Cyan3
  export __BG44_=$(  tput setb 44  || tput setab 44  || : 2>/dev/null  ); # SET BG color to DarkTurquoise
  export __BG45_=$(  tput setb 45  || tput setab 45  || : 2>/dev/null  ); # SET BG color to Turquoise2
  export __BG46_=$(  tput setb 46  || tput setab 46  || : 2>/dev/null  ); # SET BG color to Green1
  export __BG47_=$(  tput setb 47  || tput setab 47  || : 2>/dev/null  ); # SET BG color to SpringGreen2
  export __BG48_=$(  tput setb 48  || tput setab 48  || : 2>/dev/null  ); # SET BG color to SpringGreen1
  export __BG49_=$(  tput setb 49  || tput setab 49  || : 2>/dev/null  ); # SET BG color to MediumSpringGreen
  export __BG50_=$(  tput setb 50  || tput setab 50  || : 2>/dev/null  ); # SET BG color to Cyan2
  export __BG51_=$(  tput setb 51  || tput setab 51  || : 2>/dev/null  ); # SET BG color to Cyan1
  export __BG52_=$(  tput setb 52  || tput setab 52  || : 2>/dev/null  ); # SET BG color to DarkRed
  export __BG53_=$(  tput setb 53  || tput setab 53  || : 2>/dev/null  ); # SET BG color to DeepPink4
  export __BG54_=$(  tput setb 54  || tput setab 54  || : 2>/dev/null  ); # SET BG color to Purple4
  export __BG55_=$(  tput setb 55  || tput setab 55  || : 2>/dev/null  ); # SET BG color to Purple4
  export __BG56_=$(  tput setb 56  || tput setab 56  || : 2>/dev/null  ); # SET BG color to Purple3
  export __BG57_=$(  tput setb 57  || tput setab 57  || : 2>/dev/null  ); # SET BG color to BlueViolet
  export __BG58_=$(  tput setb 58  || tput setab 58  || : 2>/dev/null  ); # SET BG color to Orange4
  export __BG59_=$(  tput setb 59  || tput setab 59  || : 2>/dev/null  ); # SET BG color to Grey37
  export __BG60_=$(  tput setb 60  || tput setab 60  || : 2>/dev/null  ); # SET BG color to MediumPurple4
  export __BG61_=$(  tput setb 61  || tput setab 61  || : 2>/dev/null  ); # SET BG color to SlateBlue3
  export __BG62_=$(  tput setb 62  || tput setab 62  || : 2>/dev/null  ); # SET BG color to SlateBlue3
  export __BG63_=$(  tput setb 63  || tput setab 63  || : 2>/dev/null  ); # SET BG color to RoyalBlue1
  export __BG64_=$(  tput setb 64  || tput setab 64  || : 2>/dev/null  ); # SET BG color to Chartreuse4
  export __BG65_=$(  tput setb 65  || tput setab 65  || : 2>/dev/null  ); # SET BG color to DarkSeaGreen4
  export __BG66_=$(  tput setb 66  || tput setab 66  || : 2>/dev/null  ); # SET BG color to PaleTurquoise4
  export __BG67_=$(  tput setb 67  || tput setab 67  || : 2>/dev/null  ); # SET BG color to SteelBlue
  export __BG68_=$(  tput setb 68  || tput setab 68  || : 2>/dev/null  ); # SET BG color to SteelBlue3
  export __BG69_=$(  tput setb 69  || tput setab 69  || : 2>/dev/null  ); # SET BG color to CornflowerBlue
  export __BG70_=$(  tput setb 70  || tput setab 70  || : 2>/dev/null  ); # SET BG color to Chartreuse3
  export __BG71_=$(  tput setb 71  || tput setab 71  || : 2>/dev/null  ); # SET BG color to DarkSeaGreen4
  export __BG72_=$(  tput setb 72  || tput setab 72  || : 2>/dev/null  ); # SET BG color to CadetBlue
  export __BG73_=$(  tput setb 73  || tput setab 73  || : 2>/dev/null  ); # SET BG color to CadetBlue
  export __BG74_=$(  tput setb 74  || tput setab 74  || : 2>/dev/null  ); # SET BG color to SkyBlue3
  export __BG75_=$(  tput setb 75  || tput setab 75  || : 2>/dev/null  ); # SET BG color to SteelBlue1
  export __BG76_=$(  tput setb 76  || tput setab 76  || : 2>/dev/null  ); # SET BG color to Chartreuse3
  export __BG77_=$(  tput setb 77  || tput setab 77  || : 2>/dev/null  ); # SET BG color to PaleGreen3
  export __BG78_=$(  tput setb 78  || tput setab 78  || : 2>/dev/null  ); # SET BG color to SeaGreen3
  export __BG79_=$(  tput setb 79  || tput setab 79  || : 2>/dev/null  ); # SET BG color to Aquamarine3
  export __BG80_=$(  tput setb 80  || tput setab 80  || : 2>/dev/null  ); # SET BG color to MediumTurquoise
  export __BG81_=$(  tput setb 81  || tput setab 81  || : 2>/dev/null  ); # SET BG color to SteelBlue1
  export __BG82_=$(  tput setb 82  || tput setab 82  || : 2>/dev/null  ); # SET BG color to Chartreuse2
  export __BG83_=$(  tput setb 83  || tput setab 83  || : 2>/dev/null  ); # SET BG color to SeaGreen2
  export __BG84_=$(  tput setb 84  || tput setab 84  || : 2>/dev/null  ); # SET BG color to SeaGreen1
  export __BG85_=$(  tput setb 85  || tput setab 85  || : 2>/dev/null  ); # SET BG color to SeaGreen1
  export __BG86_=$(  tput setb 86  || tput setab 86  || : 2>/dev/null  ); # SET BG color to Aquamarine1
  export __BG87_=$(  tput setb 87  || tput setab 87  || : 2>/dev/null  ); # SET BG color to DarkSlateGray2
  export __BG88_=$(  tput setb 88  || tput setab 88  || : 2>/dev/null  ); # SET BG color to DarkRed
  export __BG89_=$(  tput setb 89  || tput setab 89  || : 2>/dev/null  ); # SET BG color to DeepPink4
  export __BG90_=$(  tput setb 90  || tput setab 90  || : 2>/dev/null  ); # SET BG color to DarkMagenta
  export __BG91_=$(  tput setb 91  || tput setab 91  || : 2>/dev/null  ); # SET BG color to DarkMagenta
  export __BG92_=$(  tput setb 92  || tput setab 92  || : 2>/dev/null  ); # SET BG color to DarkViolet
  export __BG93_=$(  tput setb 93  || tput setab 93  || : 2>/dev/null  ); # SET BG color to Purple
  export __BG94_=$(  tput setb 94  || tput setab 94  || : 2>/dev/null  ); # SET BG color to Orange4
  export __BG95_=$(  tput setb 95  || tput setab 95  || : 2>/dev/null  ); # SET BG color to LightPink4
  export __BG96_=$(  tput setb 96  || tput setab 96  || : 2>/dev/null  ); # SET BG color to Plum4
  export __BG97_=$(  tput setb 97  || tput setab 97  || : 2>/dev/null  ); # SET BG color to MediumPurple3
  export __BG98_=$(  tput setb 98  || tput setab 98  || : 2>/dev/null  ); # SET BG color to MediumPurple3
  export __BG99_=$(  tput setb 99  || tput setab 99  || : 2>/dev/null  ); # SET BG color to SlateBlue1
  export __BG100_=$( tput setb 100 || tput setab 100 || : 2>/dev/null ); # SET BG color to Yellow4
  export __BG101_=$( tput setb 101 || tput setab 101 || : 2>/dev/null ); # SET BG color to Wheat4
  export __BG102_=$( tput setb 102 || tput setab 102 || : 2>/dev/null ); # SET BG color to Grey53
  export __BG103_=$( tput setb 103 || tput setab 103 || : 2>/dev/null ); # SET BG color to LightSlateGrey
  export __BG104_=$( tput setb 104 || tput setab 104 || : 2>/dev/null ); # SET BG color to MediumPurple
  export __BG105_=$( tput setb 105 || tput setab 105 || : 2>/dev/null ); # SET BG color to LightSlateBlue
  export __BG106_=$( tput setb 106 || tput setab 106 || : 2>/dev/null ); # SET BG color to Yellow4
  export __BG107_=$( tput setb 107 || tput setab 107 || : 2>/dev/null ); # SET BG color to DarkOliveGreen3
  export __BG108_=$( tput setb 108 || tput setab 108 || : 2>/dev/null ); # SET BG color to DarkSeaGreen
  export __BG109_=$( tput setb 109 || tput setab 109 || : 2>/dev/null ); # SET BG color to LightSkyBlue3
  export __BG110_=$( tput setb 110 || tput setab 110 || : 2>/dev/null ); # SET BG color to LightSkyBlue3
  export __BG111_=$( tput setb 111 || tput setab 111 || : 2>/dev/null ); # SET BG color to SkyBlue2
  export __BG112_=$( tput setb 112 || tput setab 112 || : 2>/dev/null ); # SET BG color to Chartreuse2
  export __BG113_=$( tput setb 113 || tput setab 113 || : 2>/dev/null ); # SET BG color to DarkOliveGreen3
  export __BG114_=$( tput setb 114 || tput setab 114 || : 2>/dev/null ); # SET BG color to PaleGreen3
  export __BG115_=$( tput setb 115 || tput setab 115 || : 2>/dev/null ); # SET BG color to DarkSeaGreen3
  export __BG116_=$( tput setb 116 || tput setab 116 || : 2>/dev/null ); # SET BG color to DarkSlateGray3
  export __BG117_=$( tput setb 117 || tput setab 117 || : 2>/dev/null ); # SET BG color to SkyBlue1
  export __BG118_=$( tput setb 118 || tput setab 118 || : 2>/dev/null ); # SET BG color to Chartreuse1
  export __BG119_=$( tput setb 119 || tput setab 119 || : 2>/dev/null ); # SET BG color to LightGreen
  export __BG120_=$( tput setb 120 || tput setab 120 || : 2>/dev/null ); # SET BG color to LightGreen
  export __BG121_=$( tput setb 121 || tput setab 121 || : 2>/dev/null ); # SET BG color to PaleGreen1
  export __BG122_=$( tput setb 122 || tput setab 122 || : 2>/dev/null ); # SET BG color to Aquamarine1
  export __BG123_=$( tput setb 123 || tput setab 123 || : 2>/dev/null ); # SET BG color to DarkSlateGray1
  export __BG124_=$( tput setb 124 || tput setab 124 || : 2>/dev/null ); # SET BG color to Red3
  export __BG125_=$( tput setb 125 || tput setab 125 || : 2>/dev/null ); # SET BG color to DeepPink4
  export __BG126_=$( tput setb 126 || tput setab 126 || : 2>/dev/null ); # SET BG color to MediumVioletRed
  export __BG127_=$( tput setb 127 || tput setab 127 || : 2>/dev/null ); # SET BG color to Magenta3
  export __BG128_=$( tput setb 128 || tput setab 128 || : 2>/dev/null ); # SET BG color to DarkViolet
  export __BG129_=$( tput setb 129 || tput setab 129 || : 2>/dev/null ); # SET BG color to Purple
  export __BG130_=$( tput setb 130 || tput setab 130 || : 2>/dev/null ); # SET BG color to DarkOrange3
  export __BG131_=$( tput setb 131 || tput setab 131 || : 2>/dev/null ); # SET BG color to IndianRed
  export __BG132_=$( tput setb 132 || tput setab 132 || : 2>/dev/null ); # SET BG color to HotPink3
  export __BG133_=$( tput setb 133 || tput setab 133 || : 2>/dev/null ); # SET BG color to MediumOrchid3
  export __BG134_=$( tput setb 134 || tput setab 134 || : 2>/dev/null ); # SET BG color to MediumOrchid
  export __BG135_=$( tput setb 135 || tput setab 135 || : 2>/dev/null ); # SET BG color to MediumPurple2
  export __BG136_=$( tput setb 136 || tput setab 136 || : 2>/dev/null ); # SET BG color to DarkGoldenrod
  export __BG137_=$( tput setb 137 || tput setab 137 || : 2>/dev/null ); # SET BG color to LightSalmon3
  export __BG138_=$( tput setb 138 || tput setab 138 || : 2>/dev/null ); # SET BG color to RosyBrown
  export __BG139_=$( tput setb 139 || tput setab 139 || : 2>/dev/null ); # SET BG color to Grey63
  export __BG140_=$( tput setb 140 || tput setab 140 || : 2>/dev/null ); # SET BG color to MediumPurple2
  export __BG141_=$( tput setb 141 || tput setab 141 || : 2>/dev/null ); # SET BG color to MediumPurple1
  export __BG142_=$( tput setb 142 || tput setab 142 || : 2>/dev/null ); # SET BG color to Gold3
  export __BG143_=$( tput setb 143 || tput setab 143 || : 2>/dev/null ); # SET BG color to DarkKhaki
  export __BG144_=$( tput setb 144 || tput setab 144 || : 2>/dev/null ); # SET BG color to NavajoWhite3
  export __BG145_=$( tput setb 145 || tput setab 145 || : 2>/dev/null ); # SET BG color to Grey69
  export __BG146_=$( tput setb 146 || tput setab 146 || : 2>/dev/null ); # SET BG color to LightSteelBlue3
  export __BG147_=$( tput setb 147 || tput setab 147 || : 2>/dev/null ); # SET BG color to LightSteelBlue
  export __BG148_=$( tput setb 148 || tput setab 148 || : 2>/dev/null ); # SET BG color to Yellow3
  export __BG149_=$( tput setb 149 || tput setab 149 || : 2>/dev/null ); # SET BG color to DarkOliveGreen3
  export __BG150_=$( tput setb 150 || tput setab 150 || : 2>/dev/null ); # SET BG color to DarkSeaGreen3
  export __BG151_=$( tput setb 151 || tput setab 151 || : 2>/dev/null ); # SET BG color to DarkSeaGreen2
  export __BG152_=$( tput setb 152 || tput setab 152 || : 2>/dev/null ); # SET BG color to LightCyan3
  export __BG153_=$( tput setb 153 || tput setab 153 || : 2>/dev/null ); # SET BG color to LightSkyBlue1
  export __BG154_=$( tput setb 154 || tput setab 154 || : 2>/dev/null ); # SET BG color to GreenYellow
  export __BG155_=$( tput setb 155 || tput setab 155 || : 2>/dev/null ); # SET BG color to DarkOliveGreen2
  export __BG156_=$( tput setb 156 || tput setab 156 || : 2>/dev/null ); # SET BG color to PaleGreen1
  export __BG157_=$( tput setb 157 || tput setab 157 || : 2>/dev/null ); # SET BG color to DarkSeaGreen2
  export __BG158_=$( tput setb 158 || tput setab 158 || : 2>/dev/null ); # SET BG color to DarkSeaGreen1
  export __BG159_=$( tput setb 159 || tput setab 159 || : 2>/dev/null ); # SET BG color to PaleTurquoise1
  export __BG160_=$( tput setb 160 || tput setab 160 || : 2>/dev/null ); # SET BG color to Red3
  export __BG161_=$( tput setb 161 || tput setab 161 || : 2>/dev/null ); # SET BG color to DeepPink3
  export __BG162_=$( tput setb 162 || tput setab 162 || : 2>/dev/null ); # SET BG color to DeepPink3
  export __BG163_=$( tput setb 163 || tput setab 163 || : 2>/dev/null ); # SET BG color to Magenta3
  export __BG164_=$( tput setb 164 || tput setab 164 || : 2>/dev/null ); # SET BG color to Magenta3
  export __BG165_=$( tput setb 165 || tput setab 165 || : 2>/dev/null ); # SET BG color to Magenta2
  export __BG166_=$( tput setb 166 || tput setab 166 || : 2>/dev/null ); # SET BG color to DarkOrange3
  export __BG167_=$( tput setb 167 || tput setab 167 || : 2>/dev/null ); # SET BG color to IndianRed
  export __BG168_=$( tput setb 168 || tput setab 168 || : 2>/dev/null ); # SET BG color to HotPink3
  export __BG169_=$( tput setb 169 || tput setab 169 || : 2>/dev/null ); # SET BG color to HotPink2
  export __BG170_=$( tput setb 170 || tput setab 170 || : 2>/dev/null ); # SET BG color to Orchid
  export __BG171_=$( tput setb 171 || tput setab 171 || : 2>/dev/null ); # SET BG color to MediumOrchid1
  export __BG172_=$( tput setb 172 || tput setab 172 || : 2>/dev/null ); # SET BG color to Orange3
  export __BG173_=$( tput setb 173 || tput setab 173 || : 2>/dev/null ); # SET BG color to LightSalmon3
  export __BG174_=$( tput setb 174 || tput setab 174 || : 2>/dev/null ); # SET BG color to LightPink3
  export __BG175_=$( tput setb 175 || tput setab 175 || : 2>/dev/null ); # SET BG color to Pink3
  export __BG176_=$( tput setb 176 || tput setab 176 || : 2>/dev/null ); # SET BG color to Plum3
  export __BG177_=$( tput setb 177 || tput setab 177 || : 2>/dev/null ); # SET BG color to Violet
  export __BG178_=$( tput setb 178 || tput setab 178 || : 2>/dev/null ); # SET BG color to Gold3
  export __BG179_=$( tput setb 179 || tput setab 179 || : 2>/dev/null ); # SET BG color to LightGoldenrod3
  export __BG180_=$( tput setb 180 || tput setab 180 || : 2>/dev/null ); # SET BG color to Tan
  export __BG181_=$( tput setb 181 || tput setab 181 || : 2>/dev/null ); # SET BG color to MistyRose3
  export __BG182_=$( tput setb 182 || tput setab 182 || : 2>/dev/null ); # SET BG color to Thistle3
  export __BG183_=$( tput setb 183 || tput setab 183 || : 2>/dev/null ); # SET BG color to Plum2
  export __BG184_=$( tput setb 184 || tput setab 184 || : 2>/dev/null ); # SET BG color to Yellow3
  export __BG185_=$( tput setb 185 || tput setab 185 || : 2>/dev/null ); # SET BG color to Khaki3
  export __BG186_=$( tput setb 186 || tput setab 186 || : 2>/dev/null ); # SET BG color to LightGoldenrod2
  export __BG187_=$( tput setb 187 || tput setab 187 || : 2>/dev/null ); # SET BG color to LightYellow3
  export __BG188_=$( tput setb 188 || tput setab 188 || : 2>/dev/null ); # SET BG color to Grey84
  export __BG189_=$( tput setb 189 || tput setab 189 || : 2>/dev/null ); # SET BG color to LightSteelBlue1
  export __BG190_=$( tput setb 190 || tput setab 190 || : 2>/dev/null ); # SET BG color to Yellow2
  export __BG191_=$( tput setb 191 || tput setab 191 || : 2>/dev/null ); # SET BG color to DarkOliveGreen1
  export __BG192_=$( tput setb 192 || tput setab 192 || : 2>/dev/null ); # SET BG color to DarkOliveGreen1
  export __BG193_=$( tput setb 193 || tput setab 193 || : 2>/dev/null ); # SET BG color to DarkSeaGreen1
  export __BG194_=$( tput setb 194 || tput setab 194 || : 2>/dev/null ); # SET BG color to Honeydew2
  export __BG195_=$( tput setb 195 || tput setab 195 || : 2>/dev/null ); # SET BG color to LightCyan1
  export __BG196_=$( tput setb 196 || tput setab 196 || : 2>/dev/null ); # SET BG color to Red1
  export __BG197_=$( tput setb 197 || tput setab 197 || : 2>/dev/null ); # SET BG color to DeepPink2
  export __BG198_=$( tput setb 198 || tput setab 198 || : 2>/dev/null ); # SET BG color to DeepPink1
  export __BG199_=$( tput setb 199 || tput setab 199 || : 2>/dev/null ); # SET BG color to DeepPink1
  export __BG200_=$( tput setb 200 || tput setab 200 || : 2>/dev/null ); # SET BG color to Magenta2
  export __BG201_=$( tput setb 201 || tput setab 201 || : 2>/dev/null ); # SET BG color to Magenta1
  export __BG202_=$( tput setb 202 || tput setab 202 || : 2>/dev/null ); # SET BG color to OrangeRed1
  export __BG203_=$( tput setb 203 || tput setab 203 || : 2>/dev/null ); # SET BG color to IndianRed1
  export __BG204_=$( tput setb 204 || tput setab 204 || : 2>/dev/null ); # SET BG color to IndianRed1
  export __BG205_=$( tput setb 205 || tput setab 205 || : 2>/dev/null ); # SET BG color to HotPink
  export __BG206_=$( tput setb 206 || tput setab 206 || : 2>/dev/null ); # SET BG color to HotPink
  export __BG207_=$( tput setb 207 || tput setab 207 || : 2>/dev/null ); # SET BG color to MediumOrchid1
  export __BG208_=$( tput setb 208 || tput setab 208 || : 2>/dev/null ); # SET BG color to DarkOrange
  export __BG209_=$( tput setb 209 || tput setab 209 || : 2>/dev/null ); # SET BG color to Salmon1
  export __BG210_=$( tput setb 210 || tput setab 210 || : 2>/dev/null ); # SET BG color to LightCoral
  export __BG211_=$( tput setb 211 || tput setab 211 || : 2>/dev/null ); # SET BG color to PaleVioletRed1
  export __BG212_=$( tput setb 212 || tput setab 212 || : 2>/dev/null ); # SET BG color to Orchid2
  export __BG213_=$( tput setb 213 || tput setab 213 || : 2>/dev/null ); # SET BG color to Orchid1
  export __BG214_=$( tput setb 214 || tput setab 214 || : 2>/dev/null ); # SET BG color to Orange1
  export __BG215_=$( tput setb 215 || tput setab 215 || : 2>/dev/null ); # SET BG color to SandyBrown
  export __BG216_=$( tput setb 216 || tput setab 216 || : 2>/dev/null ); # SET BG color to LightSalmon1
  export __BG217_=$( tput setb 217 || tput setab 217 || : 2>/dev/null ); # SET BG color to LightPink1
  export __BG218_=$( tput setb 218 || tput setab 218 || : 2>/dev/null ); # SET BG color to Pink1
  export __BG219_=$( tput setb 219 || tput setab 219 || : 2>/dev/null ); # SET BG color to Plum1
  export __BG220_=$( tput setb 220 || tput setab 220 || : 2>/dev/null ); # SET BG color to Gold1
  export __BG221_=$( tput setb 221 || tput setab 221 || : 2>/dev/null ); # SET BG color to LightGoldenrod2
  export __BG222_=$( tput setb 222 || tput setab 222 || : 2>/dev/null ); # SET BG color to LightGoldenrod2
  export __BG223_=$( tput setb 223 || tput setab 223 || : 2>/dev/null ); # SET BG color to NavajoWhite1
  export __BG224_=$( tput setb 224 || tput setab 224 || : 2>/dev/null ); # SET BG color to MistyRose1
  export __BG225_=$( tput setb 225 || tput setab 225 || : 2>/dev/null ); # SET BG color to Thistle1
  export __BG226_=$( tput setb 226 || tput setab 226 || : 2>/dev/null ); # SET BG color to Yellow1
  export __BG227_=$( tput setb 227 || tput setab 227 || : 2>/dev/null ); # SET BG color to LightGoldenrod1
  export __BG228_=$( tput setb 228 || tput setab 228 || : 2>/dev/null ); # SET BG color to Khaki1
  export __BG229_=$( tput setb 229 || tput setab 229 || : 2>/dev/null ); # SET BG color to Wheat1
  export __BG230_=$( tput setb 230 || tput setab 230 || : 2>/dev/null ); # SET BG color to Cornsilk1
  export __BG231_=$( tput setb 231 || tput setab 231 || : 2>/dev/null ); # SET BG color to Grey100
  export __BG232_=$( tput setb 232 || tput setab 232 || : 2>/dev/null ); # SET BG color to Grey3
  export __BG233_=$( tput setb 233 || tput setab 233 || : 2>/dev/null ); # SET BG color to Grey7
  export __BG234_=$( tput setb 234 || tput setab 234 || : 2>/dev/null ); # SET BG color to Grey11
  export __BG235_=$( tput setb 235 || tput setab 235 || : 2>/dev/null ); # SET BG color to Grey15
  export __BG236_=$( tput setb 236 || tput setab 236 || : 2>/dev/null ); # SET BG color to Grey19
  export __BG237_=$( tput setb 237 || tput setab 237 || : 2>/dev/null ); # SET BG color to Grey23
  export __BG238_=$( tput setb 238 || tput setab 238 || : 2>/dev/null ); # SET BG color to Grey27
  export __BG239_=$( tput setb 239 || tput setab 239 || : 2>/dev/null ); # SET BG color to Grey30
  export __BG240_=$( tput setb 240 || tput setab 240 || : 2>/dev/null ); # SET BG color to Grey35
  export __BG241_=$( tput setb 241 || tput setab 241 || : 2>/dev/null ); # SET BG color to Grey39
  export __BG242_=$( tput setb 242 || tput setab 242 || : 2>/dev/null ); # SET BG color to Grey42
  export __BG243_=$( tput setb 243 || tput setab 243 || : 2>/dev/null ); # SET BG color to Grey46
  export __BG244_=$( tput setb 244 || tput setab 244 || : 2>/dev/null ); # SET BG color to Grey50
  export __BG245_=$( tput setb 245 || tput setab 245 || : 2>/dev/null ); # SET BG color to Grey54
  export __BG246_=$( tput setb 246 || tput setab 246 || : 2>/dev/null ); # SET BG color to Grey58
  export __BG247_=$( tput setb 247 || tput setab 247 || : 2>/dev/null ); # SET BG color to Grey62
  export __BG248_=$( tput setb 248 || tput setab 248 || : 2>/dev/null ); # SET BG color to Grey66
  export __BG249_=$( tput setb 249 || tput setab 249 || : 2>/dev/null ); # SET BG color to Grey70
  export __BG250_=$( tput setb 250 || tput setab 250 || : 2>/dev/null ); # SET BG color to Grey74
  export __BG251_=$( tput setb 251 || tput setab 251 || : 2>/dev/null ); # SET BG color to Grey78
  export __BG252_=$( tput setb 252 || tput setab 252 || : 2>/dev/null ); # SET BG color to Grey82
  export __BG253_=$( tput setb 253 || tput setab 253 || : 2>/dev/null ); # SET BG color to Grey85
  export __BG254_=$( tput setb 254 || tput setab 254 || : 2>/dev/null ); # SET BG color to Grey89
  export __BG255_=$( tput setb 255 || tput setab 255 || : 2>/dev/null ); # SET BG color to Grey93


##INFO for other scripts of mine which would redefine these
export __TPUT_256COLORS_DEFINED="true"



}

__define_tput_colors_additional_256terms

